name: SDK CI
on:
  push:
    branches: [ main, master ]

env:
  DOXYFILE: ${{github.workspace}}/Doxyfile
  HTML_DIR: ${{github.workspace}}/doc/html

jobs:
  build:
    runs-on: ubuntu-latest
    environment: linux
    steps:
      - uses: actions/checkout@v3

      - name: Setup GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.6.0

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install doxygen
        run: |
          sudo apt-get install doxygen -y
          sudo apt install graphviz -y

      - name: Run Build Documentation Script
        run: |
          chmod +x ./build-doc.sh
          ./build-doc.sh

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc/html
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages

      - name: Run Example Build Script
        run: |
          chmod +x ./test-build-examples.sh
          ./test-build-examples.sh


